name: Deploy apk and roll update

on:
  push:
    branches:
      - apk-deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Run build and roll script on server
        uses: appleboy/ssh-action@v0.1.7
        with: 
          host: ${{ secrets.EC2_HOST }}
          port: ${{ secrets.EC2_PORT }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: bash -lc /home/anime-updates/roll-apk-update.sh

