name: Deploy apk and roll update

on:
  push:
    branches:
      - apk-deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Run build and roll script on server
        uses: appleboy/ssh-action@v0.1.7
        with: 
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: /home/anime-updates/roll-apk-update.sh

