name: APK Deployment

on:
  push:
    branches:
      - apk-deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Restore secret files
      - name: Restore Firebase config files
        run: |
          mkdir -p lib/config
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > android/app/google-services.json
          echo "${{ secrets.FIREBASE_CONFIG_DART }}" | base64 --decode > lib/config/firebase_config.dart

      # 3. Setup Flutter pinned version
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.22.2

      # 4. Cache Flutter SDK, Pub & Gradle for faster builds
      - name: Cache Flutter & Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            $HOME/flutter/bin/cache
            ~/.gradle
          key: ${{ runner.os }}-flutter-3.22.2-${{ hashFiles('**/pubspec.yaml') }}

      # 5. Install minimal Android SDK
      - name: Install Android SDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-35" "build-tools;34.0.0"

      # 6. Get Flutter dependencies
      - name: Get Flutter dependencies
        run: flutter pub get

      # 7. Build APK
      - name: Build APK
        run: flutter build apk --release -v

      - name: Move APK to workspace root
        run: cp build/app/outputs/apk/release/anime-updates*.apk ./

      # 8. Upload APK to VPS
      - name: Upload APK to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          source: ./anime-updates*.apk
          target: ${{ secrets.SERVER_APK_PATH }}
